#! python3

import re, pyperclip

# TODO: Create a regex for Phone numbers

phoneRegex = re.compile(r'''
# 415-555-0000, 555-0000, (412) 555-0000, 555-0000 ext. 12345, x12345
(
((\d\d\d) | (\(\d\d\d\)))?	# area code ? = zero or 1 time
(\s | \-) 					# first seperator
\d\d\d						# first 3 digits
-							# seperator
\d\d\d\d					# last 4 digits
((ext(\.)? \s | x) 			# extension word-part
(\d{2,5}))? 				# Extension number-part
)
 ''', re.VERBOSE)
# TODO: Create a regex for email address
emailRegex = re.compile(r'''
# some.+_things@something.com
[a-zA-Z0-9._+]+ # name [custom character class], + = 1 or more
@ 				# @
[a-zA-Z0-9._+]+ # domain

	''', re.VERBOSE)


# TODO: Get the text off the clipboard
text = pyperclip.paste()

# TODO: Extract the email/phone from this text
extractPhone = phoneRegex.findall(text)
extractEmail = emailRegex.findall(text)

allPhoneNumbers = []
allEmailAddress = []

for phoneNumber in extractPhone:
	allPhoneNumbers.append(phoneNumber[0])

for emailAddress in extractEmail:
	allEmailAddress.append(emailAddress)

# TODO: Copy the extracted email/phone to the clipboard



results = '\n'.join(allPhoneNumbers) + '\n' + '\n'.join(allEmailAddress)

print(results)
pyperclip.copy(results) #copy results to clipboard



